package com.gettler.controlcenter.mapper;

import com.gettler.controlcenter.pojo.Port;
import com.gettler.controlcenter.pojo.PortExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Sun May 08 16:19:53 CST 2022
     */
    int countByExample(PortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Sun May 08 16:19:53 CST 2022
     */
    int deleteByExample(PortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Sun May 08 16:19:53 CST 2022
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Sun May 08 16:19:53 CST 2022
     */
    int insert(Port record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Sun May 08 16:19:53 CST 2022
     */
    int insertSelective(Port record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Sun May 08 16:19:53 CST 2022
     */
    List<Port> selectByExample(PortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Sun May 08 16:19:53 CST 2022
     */
    Port selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Sun May 08 16:19:53 CST 2022
     */
    int updateByExampleSelective(@Param("record") Port record, @Param("example") PortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Sun May 08 16:19:53 CST 2022
     */
    int updateByExample(@Param("record") Port record, @Param("example") PortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Sun May 08 16:19:53 CST 2022
     */
    int updateByPrimaryKeySelective(Port record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Sun May 08 16:19:53 CST 2022
     */
    int updateByPrimaryKey(Port record);
}