package com.gettler.controlcenter.pojo;

public class Port {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column port.userid
     *
     * @mbggenerated Sat May 07 18:36:52 CST 2022
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column port.num
     *
     * @mbggenerated Sat May 07 18:36:52 CST 2022
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column port.userid
     *
     * @return the value of port.userid
     *
     * @mbggenerated Sat May 07 18:36:52 CST 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column port.userid
     *
     * @param userid the value for port.userid
     *
     * @mbggenerated Sat May 07 18:36:52 CST 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column port.num
     *
     * @return the value of port.num
     *
     * @mbggenerated Sat May 07 18:36:52 CST 2022
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column port.num
     *
     * @param num the value for port.num
     *
     * @mbggenerated Sat May 07 18:36:52 CST 2022
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}